from unittest import TestCase
from typing import Type, TypeVar

_E = TypeVar('_E', bound=Exception)

class RetypeTestCase(TestCase):
    def assertReapply(self, pyi_txt: str, src_txt: str, expected_txt: str) -> None: ...
    def assertReapplyVisible(self, pyi_txt: str, src_txt: str, expected_txt: str) -> None: ...
    def assertReapplyRaises(self, pyi_txt: str, src_txt: str, expected_exception: Type[_E]) -> _E: ...
