dist: xenial
language: python
cache: pip

env:
  TOXENV=py

jobs:
  include:
  - name: "check wheel metadata correct"
    python: 3.7
    env:
    - TOXENV=package_readme
  - name: "type checker"
    python: 3.7
    env:
    - TOXENV=type
  - name: "style checker"
    python: 3.7
    env:
    - TOXENV=lint
  - name: "test dev env creation"
    python: 3.7
    env:
    - TOXENV=dev
  - name: "format checker"
    python: 3.7
    env:
    - TOXENV=format-check
  - name: "run test suite with python 3.6"
    python: 3.6
  - name: "run test suite with python 3.7"
    python: 3.7
  - name: "run test suite with python 3.8-dev"
    python: 3.8-dev
  - name: "run ourselves on our stubs"
    python: 3.7
    env:
    - TOXENV=merge


install:
- sudo apt-get -y install pandoc
- pip install -U pip setuptools
- pip install -U --force-reinstall tox==3.9.0
- tox --notest --skip-missing-interpreters false -vv

script:
- tox
