name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PYTEST_XDIST_PROC_NR: 'auto'
  CI_RUN: 'yes'

jobs:
- template: run-tox-env.yml@tox
  parameters:
    jobs:
      format_check: null
      merge: null
      type: null
      lint: null
      package_readme: null
      py38:
        image: [linux]
      py37:
        image: [linux, windows, macOs]
      py36:
        image: [linux, windows, macOs]
      dev: null
    coverage:
      with_toxenv: 'coverage' # generate .tox/.coverage, .tox/coverage.xml after test run
      for_envs: [py38, py37, py36]
