from pathlib import Path
from typing import Iterator, List, Optional, Tuple, Union

from lib2to3.pytree import Node, Leaf
from typed_ast import ast3

def new(n: Union[Node, Leaf], prefix: str = None) -> Union[Node, Leaf]: ...
def get_annotated_param(node: Union[Node, Leaf], arg: ast3.arg, *, missing_ok: bool = False) -> Union[Node, Leaf]: ...
def gen_annotated_params(args: ast3.arguments, defaults: List[Optional[ast3.AST]], params: List[Union[Node, Leaf]], *, implicit_default: bool = False, is_method: bool = False) -> Iterator[Union[Node, Leaf]]: ...
def pop_param(params: List[Union[Node, Leaf]]) -> Tuple[Union[Node, Leaf], Union[Node, Leaf, None]]: ...
def minimize_whitespace(text: str) -> str: ...
def annotate_return(function: Node, ast_returns: Optional[ast3.AST], offset: int) -> None: ...
def annotate_parameters(parameters: Node, ast_args: ast3.arguments, *, is_method: bool = False) -> None: ...
def append_after_imports(stmt_to_insert: Node, node: Node) -> None: ...
def make_import(*names: ast3.alias, from_module: str = None) -> Node: ...
def names_already_imported(names: Union[List[ast3.AST], ast3.AST], node: Node) -> bool: ...
def reapply(ast_node: ast3.AST, lib2to3_node: Node) -> Node: ...
def lib2to3_parse(src_txt: str) -> Node: ...
def lib2to3_unparse(node: Node) -> str: ...
def retype_file(pyi: Path, srcs: Path, targets: Path) -> Path: ...
def retype_path(path: Path, srcs: Path, targets: Path) -> Iterator[Tuple[Path, str]]: ...
def main(src_dir: str, pyi_dir: str, target_dir: str) -> None: ...
