from pathlib import Path
from typing import Iterator, List, Optional, Tuple, Union

from lib2to3.pytree import Node, Leaf
from typed_ast import ast3

def new(n: Union[Node, Leaf], prefix: str = None) -> Union[Node, Leaf]: ...
def get_annotated_param(node: Union[Node, Leaf], arg: ast3.arg, *, missing_ok: bool = False) -> Union[Node, Leaf]: ...
def gen_annotated_params(args: ast3.arguments, defaults: List[Optional[ast3.AST]], params: List[Union[Node, Leaf]], *, implicit_default: bool = False, is_method: bool = False) -> Iterator[Union[Node, Leaf]]: ...
def pop_param(params: List[Union[Node, Leaf]]) -> Tuple[Union[Node, Leaf], Union[Node, Leaf, None]]: ...
def minimize_whitespace(text: str) -> str: ...
def annotate_return(function: Node, ast_returns: Optional[ast3.AST], offset: int) -> None: ...
def annotate_parameters(parameters: Node, ast_args: ast3.arguments, *, is_method: bool = False) -> None:
    typedargslist: List[Union[Node, Leaf]]
    defaults: List[Optional[ast3.AST]]

def append_after_imports(stmt_to_insert: Node, node: Node) -> None: ...
def make_import(*names: ast3.alias, from_module: str = None) -> Node: ...
def is_builtin_method_decorator(name: str) -> bool: ...
def decorator_names(obj: Union[Node, ast3.AST, List[Union[Node, ast3.AST]]]) -> List[str]: ...
def names_already_imported(names: Union[List[ast3.AST], ast3.AST], node: Node) -> bool: ...
def reapply(ast_node: ast3.AST, lib2to3_node: Node) -> Node: ...
def lib2to3_parse(src_txt: str) -> Node: ...
def lib2to3_unparse(node: Node) -> str: ...
def retype_file(pyi: Path, srcs: Path, targets: Path) -> Path: ...
def retype_path(path: Path, srcs: Path, targets: Path) -> Iterator[Tuple[Path, str]]: ...
def main(src_dir: str, pyi_dir: str, target_dir: str) -> None: ...

# internal singledispatch implementations, etc.
def _r_list(l: List[ast3.AST], lib2to3_node: Node) -> None: ...
def _r_importfrom(import_from: ast3.ImportFrom, node: Node) -> None: ...
def _r_import(import_: ast3.Import, node: Node) -> None: ...
def _r_classdef(cls: ast3.ClassDef, node: Node) -> None: ...
def _r_functiondef(fun: ast3.FunctionDef, node: Node) -> None: ...
def _r_annassign(annassign: ast3.AnnAssign, body: Node) -> None: ...

def _nai_list(names: List[ast3.alias], node: Node) -> bool: ...
def _nai_alias(alias: ast3.alias, node: Node) -> bool: ...

def _dn_list(l: List[Union[Node, ast3.AST]]) -> List[str]: ...
def _dn_node(node: Node) -> List[str]: ...
def _dn_name(name: ast3.Name) -> List[str]: ...
def _dn_call(call: ast3.Call) -> List[str]: ...
def _dn_attribute(attr: ast3.Attribute) -> List[str]: ...
